- hosts: staging
  tasks:
    - name: Install required build packages
      apt:
        name: ["git"]

    - name: Add the user "cast" with a bash shell
      user:
        name: cast
        shell: /bin/bash

    - name: Git checkout repository
      git:
        repo: "https://github.com/ephes/cast_hosting"
        dest: /home/cast/site
      become: true
      become_user: cast

    - name: Install poetry
      shell: curl -sSL https://raw.githubusercontent.com/python-poetry/poetry/master/get-poetry.py | /usr/local/bin/python3.9
      args:
        warn: no
      become: true
      become_user: cast

    - name: Replace python3 in poetry bin with python3.9 :(
      lineinfile:
        path: /home/cast/.poetry/bin/poetry
        regexp: "python3"
        line: "#!/usr/bin/env python3.9"

    - name: Install poetry dependencies
      shell: /home/cast/.poetry/bin/poetry install
      args:
        chdir: /home/cast/site
      become: true
      become_user: cast

    # Gunicorn
    - name: Create a symbolic link for gunicorn systemd service
      file:
        src: /home/cast/site/cast.service
        dest: /etc/systemd/system/cast.service
        state: link

    - name: Make sure cast gunicorn service is running
      systemd:
        state: restarted
        name: 

    - name: Create a symbolic link for traefik loadbalancer
      file:
        src: /home/cast/site/cast.traefik.yml
        dest: /etc/traefik/dynamic/cast.traefik.yml
        state: link