http:
  routers:
    cast-router:
      rule: "Host(`django-cast.com`) || Host(`www.django-cast.com`) || Host(`staging.wersdoerfer.de`) || Host(`staging.python-podcast.de`)"

      entryPoints:
        - web
      middlewares:
        - redirect
        - csrf
      service: django

    cast-secure-router:
      rule: "Host(`django-cast.com`) || Host(`www.django-cast.com`) || Host(`staging.wersdoerfer.de`) || Host(`staging.python-podcast.de`)"

      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        certResolver: letsencrypt

  middlewares:
    redirect:
      redirectScheme:
        scheme: https
        permanent: true
    csrf:
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://localhost:8001
