http:
  routers:
    web-router:
      rule: "Host(`django-cast.com`) || Host(`www.django-cast.com`)"

      entryPoints:
        - web
      middlewares:
        - redirect
        - csrf
      service: django

    web-secure-router:
        rule: "Host(`django-cast.com`) || Host(`www.django-cast.com`)"

      entryPoints:
        - web-secure
      middlewares:
        - csrf
      service: django
      tls:
        certResolver: letsencrypt

  middlewares:
    redirect:
      redirectScheme:
        scheme: https
        permanent: true
    csrf:
      headers:
        hostsProxyHeaders: ["X-CSRFToken"]

  services:
    django:
      loadBalancer:
        servers:
          - url: http://localhost:8001
