name: Deploy on Push
on: [push]
jobs:
  deployment:
    runs-on: ubuntu-latest
    steps:
      - uses: fjogeleit/http-request-action@master
        with:
          url: 'https://2c1d1280af9c.ngrok.io/deploy'
          method: 'POST'
